config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update", as: :tasks_update
  delete "tasks/:id", to: "tasks#destroy"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :tasks_edit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end


  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
  params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>EDIT TASK</h1>

<%= form_for(@task) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>


 <P><%= link_to "UPDATE TASK", tasks_update_path %></P>

app/views/tasks/index.html.erb
<h1>MY TASKS</h1>

<% @tasks.each do |task| %>
  <% if task.completed %>
    <li>
      <input type="checkbox" name="checkbox" checked>
      <label for="checkbox"> <%= link_to task.title, task_path(task) %></label>
    </li>

  <% else %>
    <li>
      <input type="checkbox" name="checkbox"> <label for="checkbox"> <%= link_to task.title, task_path(task) %></label>
    </li>
  <% end %>
    <p><%= link_to "Delete", task_path(task), method: :delete%></p>
<% end %>


 <P><%= link_to "+ Add a new task ✍", tasks_new_path %></P>

app/views/tasks/new.html.erb
<h1>NEW TASK</h1>

<%= form_for(@task) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= link_to f.submit, tasks_path %>

<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to "Edit this task", tasks_edit_path %>


<div>
  <p><%= @task.details %></p>
</div>
<% if @task.completed %>
  <input type="checkbox" name="checkbox" checked> <label for="checkbox"> task is completed</label>
<% else %>
  <input type="checkbox" name="checkbox"> <label for="checkbox"> task is not completed<br></label>
<% end %>


<%= link_to "Back to all tasks", tasks_path %>